// Admin Supabase Configuration (loaded from .env.local)
// ⚠️ THIS FILE IS GENERATED — DO NOT COMMIT WITH REAL KEYS

window.SUPABASE_URL = 'https://hhywrvedlwljawgxzpkq.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoeXdydmVkbHdsamF3Z3h6cGtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU1MzM4OTgsImV4cCI6MjEwMTEwOTg5OH0.GXHRDayBNRbWh1QywGkYCJ6D79qnm_mtyRSJUxw4x50';
window.SUPABASE_SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoeXdydmVkbHdsamF3Z3h6cGtxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NTUzMzg5OCwiZXhwIjoyMTAxMTA5ODk4fQ.cJsO8_0V6LKVvbb11T3rlfK-adt3YyRFDk3QspUaFIU';
