name: Deploy Kasir Gerobak

on:
  workflow_call:
  push:
    paths:
      - 'gerobak/**'
      - 'gerobak/.vercel/**'
  pull_request:
    paths:
      - 'gerobak/**'
      - 'gerobak/.vercel/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        id: vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_GEROBAK }}
          working-directory: ./gerobak
          vercel-args: '--prod'
          scope: ${{ secrets.VERCEL_SCOPE }}

      - name: Get Vercel Preview URL
        if: github.event_name == 'pull_request'
        run: |
          echo "Preview URL: ${{ steps.vercel.outputs['preview-url'] }}"

      - name: Get Vercel Production URL
        if: github.event_name == 'push'
        run: |
          echo "Production URL: ${{ steps.vercel.outputs['production-url'] }}"
